<?php

namespace Media\MediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Media\MediaBundle\Controller\PageController();
        return $instance;
    }
}
